In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git
!huggingface-cli login --token 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

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid.
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [3]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_id = "bigcode/starcoderbase"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
model_4bit = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map="auto")

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
CUDA SETUP: CUDA runtime path found: /opt/conda/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...


/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/lib/x86_64-linux-gnu'), PosixPath('/usr/local/cuda/lib')}
  warn(msg)
/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)


Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]

In [4]:
model_4bit.hf_device_map

{'': 0}

In [23]:
import time

def generation(text, device, max_new_tokens=50):
    st = time.time()
    device = "cuda:0"
    inputs = tokenizer(text, return_tensors="pt").to(device)

    outputs = model_4bit.generate(**inputs, max_new_tokens=max_new_tokens)
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))
    et = time.time()
    print("# get the execution time:",et - st)
    

In [15]:
text = '''recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#Summarize:'''
generation(text, "cuda:0")

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#Summarize:
	print(recur_factorial(5))
	print(recur_factorial(10))
	print(recur_factorial(20))
	print(recur_factorial(30))
	print
# get the execution time: 32.43457770347595


In [16]:
text = '''recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#This'''
generation(text, "cuda:0")

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#This is the function that will be called to calculate the factorial of a number
	factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(
# get the execution time: 32.42167592048645


In [17]:
text = '''recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#This function'''
generation(text, "cuda:0")

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#This function will take a vector of numbers and return the factorial of each number in the vector
	factorial <- function(x) {
	return(sapply(x, recur_factorial))
	}
	#This function will
# get the execution time: 32.420104026794434


In [24]:
text = '''
recur_factorial <- function(n) {
if(n <= 1) {
return(1)
} else { 
return(n * recur_factorial(n-1))
}
}
#Think step by step and write a final summary that states the functionality of the code above:
'''
generation(text, "cuda:0", max_new_tokens=100)

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#Think step by step and write a final summary that states the functionality of the code above:
	#1. The function takes in a number n and returns the factorial of n.
	#2. The function starts by checking if n is less than or equal to 1. If it is, the function returns 1.
	#3. If n is greater than 1, the function returns n times the factorial of n-1.
	#4. The function is recursive.
	#5. The function is named recur_factorial
# get the execution time: 64.76068353652954


# HF Inference API

In [25]:
import requests
import time

API_URL = "https://api-inference.huggingface.co/models/bigcode/starcoder"
headers = {"Authorization": "Bearer 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"}

def query(payload):
    st = time.time()
    response = requests.post(API_URL, headers=headers, json=payload)
    et = time.time()
    print("# get the execution time:",et - st)
    return response.json()

In [27]:



output = query({
	"inputs": '''
recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#Think step by step and write a final summary that states the functionality of the code above:''',
    "parameters": {"max_new_tokens":250}
})

print(output[0]['generated_text'])

# get the execution time: 0.30684423446655273

	#1. What does the function do?
	#The function takes in a number and returns the factorial of that number.
	#2. What are the inputs?
	#The function takes in a number.
	#3. What are the outputs?
	#The function returns the factorial of the number.
	#4. What are the general steps?
	#The function takes in a number and checks if it is less than or equal to 1. If it is, the function returns 1. If it is not, the function returns the number multiplied by the factorial of the number minus 1.
	#5. What happens if the input is 0?
	#The function returns 1.
	#6. What happens if the input is negative?
	#The function returns an error.
	#7. What happens if the input is a decimal?
	#The function returns an error.
	#8. What happens if the input is a string?
	#The function returns an error.
	#9. What happens if the input is a vector?
	#The function returns an


In [8]:
output

{'error': 'Service Unavailable'}

In [4]:
print(output)

[{'generated_text': '\n\t#1. What does the function do?\n\t#The function takes in a number and returns the factorial of that number.\n\t#2. What are the inputs?\n\t#The function takes in a number.\n\t#3. What are the outputs?\n\t#The function returns the factorial of the number.\n\t#4. What are the general steps?\n\t#The function takes in a number and checks if it is less than or equal to 1. If it is, the function returns 1. If it is not, the function returns the number multiplied by the factorial of the number minus 1.\n\t#5. What happens if the input is 0?\n\t#The function returns 1.\n\t#6. What happens if the input is negative?\n\t#The function returns an error.\n\t#7. What happens if the input is a decimal?\n\t#The function returns an error.\n\t#8. What happens if the input is a string?\n\t#The function returns an error.\n\t#9. What happens if the input is a vector?\n\t#The function returns an'}]


### Random

In [18]:
from transformers import RobertaConfig, RobertaTokenizer, RobertaConfig, RobertaForMaskedLM, T5ForConditionalGeneration
victim_model = dict()
victim_model['model'] = T5ForConditionalGeneration.from_pretrained('Salesforce/codet5-base-multi-sum')
victim_model['tokenizer'] = RobertaTokenizer.from_pretrained('Salesforce/codet5-base')
victim_model['model'].to('cuda:0')


T5ForConditionalGeneration(
  (shared): Embedding(32100, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32100, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dro

In [4]:
def _tokenize(seq, tokenizer, config):
    if config['do_lower'] == 1:
        seq = seq.replace('\n', '').lower()
    else:
        seq = seq.replace('\n', '')
    seq = " ".join(seq.split())
    words = seq.split(' ')

    sub_words = []
    keys = []
    index = 0
    for word in words:
        # Breaking a word into subwords
        sub = tokenizer.tokenize(word)
        sub_words += sub
        # `keys`: Stores the starting and the ending index of each word. This is important
        # because each word is broken into sub-words and we need to keep a track of 
        # each word's starting and ending index in the `sub_words` list.
        keys.append([index, index + len(sub)])
        index += len(sub)

    return words, sub_words, keys, seq

In [5]:
config = dict()
config['do_lower'] = 0
seq = '''
recur_factorial <- function(n) {
	if(n <= 1) {
	return(1)
	} else { 
	return(n * recur_factorial(n-1))
	}
	}
	#Think step by step and write a final summary that states the functionality of the code above:'''
# Preparing the code for input to the victim model
words, sub_words, keys, input_code = _tokenize(seq, victim_model['tokenizer'], config)

In [6]:
words, sub_words, keys, input_code

(['recur_factorial',
  '<-',
  'function(n)',
  '{',
  'if(n',
  '<=',
  '1)',
  '{',
  'return(1)',
  '}',
  'else',
  '{',
  'return(n',
  '*',
  'recur_factorial(n-1))',
  '}',
  '}',
  '#Think',
  'step',
  'by',
  'step',
  'and',
  'write',
  'a',
  'final',
  'summary',
  'that',
  'states',
  'the',
  'functionality',
  'of',
  'the',
  'code',
  'above:'],
 ['re',
  'cur',
  '_',
  'factor',
  'ial',
  '<',
  '-',
  'function',
  '(',
  'n',
  ')',
  '{',
  'if',
  '(',
  'n',
  '<',
  '=',
  '1',
  ')',
  '{',
  'return',
  '(',
  '1',
  ')',
  '}',
  'else',
  '{',
  'return',
  '(',
  'n',
  '*',
  're',
  'cur',
  '_',
  'factor',
  'ial',
  '(',
  'n',
  '-',
  '1',
  '))',
  '}',
  '}',
  '#',
  'Th',
  'ink',
  'step',
  'by',
  'step',
  'and',
  'write',
  'a',
  'final',
  'summary',
  'that',
  'states',
  'the',
  'function',
  'ality',
  'of',
  'the',
  'code',
  'above',
  ':'],
 [[0, 5],
  [5, 7],
  [7, 11],
  [11, 12],
  [12, 15],
  [15, 17],
  [17, 19],
  [19

In [12]:
import torch
code_tokens = victim_model['tokenizer'].encode_plus(input_code, None, add_special_tokens=True, max_length=256)
code_ids  = torch.tensor(code_tokens["input_ids"]).unsqueeze(0)
code_mask = code_ids.ne(victim_model['tokenizer'].pad_token_id).to('cuda:0')
attention_mask = code_ids.ne(1)

In [15]:
config['task']='summarize'

In [19]:
pred = victim_model['model'].generate(code_ids.to('cuda:0'), 
                                            attention_mask=code_mask,
                                            output_scores=True,
                                            return_dict_in_generate=True,
                                            early_stopping=config['task']=='summarize',
                                            max_length=128)    
pred_out = victim_model['tokenizer'].batch_decode(pred.sequences[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)


In [20]:
pred

GreedySearchEncoderDecoderOutput(sequences=tensor([[   0,    1,  426, 1397, 5578,  649,  445,    2]], device='cuda:0'), scores=(tensor([[13.3469, 27.3201,  5.3753,  ..., -1.1422, -1.2316,  5.4480]],
       device='cuda:0'), tensor([[-0.6997,  3.8999,  1.5526,  ..., -1.0422, -0.7205, -0.0165]],
       device='cuda:0'), tensor([[-0.9442,  3.0143,  3.4130,  ..., -1.1824, -1.3171, -0.1500]],
       device='cuda:0'), tensor([[-0.9320,  0.4556,  6.0750,  ..., -3.2853, -1.9187, -1.7146]],
       device='cuda:0'), tensor([[-1.0481, -0.0892,  6.8627,  ..., -2.7920, -1.5968, -1.8748]],
       device='cuda:0'), tensor([[-1.1265, -0.0943,  9.2610,  ..., -4.3646, -1.2831, -1.9783]],
       device='cuda:0'), tensor([[-0.6953, -0.1987, 14.1601,  ..., -4.7066, -3.7979, -2.6662]],
       device='cuda:0')), encoder_attentions=None, encoder_hidden_states=None, decoder_attentions=None, cross_attentions=None, decoder_hidden_states=None)

In [21]:
pred_out

['<pad>', '<s>', 'Re', 'cur', ' factor', 'ial', ' function', '</s>']

In [22]:
scores = pred.scores
scores

(tensor([[13.3469, 27.3201,  5.3753,  ..., -1.1422, -1.2316,  5.4480]],
        device='cuda:0'),
 tensor([[-0.6997,  3.8999,  1.5526,  ..., -1.0422, -0.7205, -0.0165]],
        device='cuda:0'),
 tensor([[-0.9442,  3.0143,  3.4130,  ..., -1.1824, -1.3171, -0.1500]],
        device='cuda:0'),
 tensor([[-0.9320,  0.4556,  6.0750,  ..., -3.2853, -1.9187, -1.7146]],
        device='cuda:0'),
 tensor([[-1.0481, -0.0892,  6.8627,  ..., -2.7920, -1.5968, -1.8748]],
        device='cuda:0'),
 tensor([[-1.1265, -0.0943,  9.2610,  ..., -4.3646, -1.2831, -1.9783]],
        device='cuda:0'),
 tensor([[-0.6953, -0.1987, 14.1601,  ..., -4.7066, -3.7979, -2.6662]],
        device='cuda:0'))

In [23]:
scores = torch.stack(list(scores)).squeeze()
print('*'*100)
print(scores)
pred_scores, pred_indices = torch.max(scores, dim=1)
print('*'*100)
print(pred_scores)
print('*'*100)
print(pred_indices)
pred_score = torch.sum(torch.tensor(pred_scores))
print('*'*100)
print(pred_score)

****************************************************************************************************
tensor([[ 1.3347e+01,  2.7320e+01,  5.3753e+00,  ..., -1.1422e+00,
         -1.2316e+00,  5.4480e+00],
        [-6.9966e-01,  3.8999e+00,  1.5526e+00,  ..., -1.0422e+00,
         -7.2046e-01, -1.6539e-02],
        [-9.4418e-01,  3.0143e+00,  3.4130e+00,  ..., -1.1824e+00,
         -1.3171e+00, -1.4998e-01],
        ...,
        [-1.0481e+00, -8.9196e-02,  6.8627e+00,  ..., -2.7920e+00,
         -1.5968e+00, -1.8748e+00],
        [-1.1265e+00, -9.4340e-02,  9.2610e+00,  ..., -4.3646e+00,
         -1.2831e+00, -1.9783e+00],
        [-6.9534e-01, -1.9870e-01,  1.4160e+01,  ..., -4.7066e+00,
         -3.7979e+00, -2.6662e+00]], device='cuda:0')
****************************************************************************************************
tensor([27.3201, 11.4927, 20.3274, 11.8502, 21.3518, 11.9610, 14.1601],
       device='cuda:0')
*****************************************************

/tmp/ipykernel_28/3421539484.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred_score = torch.sum(torch.tensor(pred_scores))
